### ISSUE TITLE
It doesn't remove my messages, but also no fails

### ISSUE THREAD

**Issue by tdoerrich** [yunabsd/SlackRemoveMe#1]
I did the NPM steps.

1. Download project
2. npm install (in the project folder)
3. npm install async
4. npm install superagent
5. node removeme.js
6. 
`latest time: xxxxxxxx.xxx
count: 0
delete start
complete `

But none of the messages are removed (which makes sense since it says _count: 0_ but there are a lot of messages there. What am I doing wrong?

**Comment by yunabsd** [comment]
Lastest message time is incorectry in my source.
I modified source, and commited.
You can edit source directly, removeme.js 17 line

// removeme.js line 17
`let latest = '0';`

And you have to get a slack legacy token.
https://api.slack.com/custom-integrations/legacy-tokens

```
const token = 'xoxp-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';  // <- edit
```

**Comment by tdoerrich** [comment]
Got it! Thanks. :D
